# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pricer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpricer.proto\x12\x10optionpricer.api\"\xcf\x01\n\x0eOptionContract\x12\x0e\n\x06strike\x18\x01 \x03(\x01\x12\x0e\n\x06\x65xpiry\x18\x02 \x03(\x01\x12\x31\n\x0boption_type\x18\x03 \x01(\x0e\x32\x1c.optionpricer.api.OptionType\x12\x10\n\x08\x61merican\x18\x04 \x01(\x08\x12\x31\n\x0b\x65xotic_type\x18\x05 \x01(\x0e\x32\x1c.optionpricer.api.ExoticType\x12\x15\n\rbarrier_level\x18\x06 \x03(\x01\x12\x0e\n\x06rebate\x18\x07 \x03(\x01\"O\n\x0bMarketState\x12\x0c\n\x04spot\x18\x01 \x03(\x01\x12\x0c\n\x04rate\x18\x02 \x03(\x01\x12\x12\n\nvolatility\x18\x03 \x03(\x01\x12\x10\n\x08\x64ividend\x18\x04 \x03(\x01\"\x82\x01\n\x0ePricingRequest\x12\x32\n\x08\x63ontract\x18\x01 \x01(\x0b\x32 .optionpricer.api.OptionContract\x12-\n\x06market\x18\x02 \x01(\x0b\x32\x1d.optionpricer.api.MarketState\x12\r\n\x05model\x18\x03 \x01(\t\"\xb3\x01\n\x0fPricingResponse\x12\x0e\n\x06prices\x18\x01 \x03(\x01\x12=\n\x06greeks\x18\x02 \x03(\x0b\x32-.optionpricer.api.PricingResponse.GreeksEntry\x12\"\n\x1a\x63ompute_time_ns_per_option\x18\x03 \x01(\x01\x1a-\n\x0bGreeksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01*\x1f\n\nOptionType\x12\x08\n\x04\x43\x41LL\x10\x00\x12\x07\n\x03PUT\x10\x01*r\n\nExoticType\x12\x0b\n\x07VANILLA\x10\x00\x12\t\n\x05\x41SIAN\x10\x01\x12\x0c\n\x08LOOKBACK\x10\x02\x12\x0e\n\nBARRIER_UI\x10\x03\x12\x0e\n\nBARRIER_UO\x10\x04\x12\x0e\n\nBARRIER_DI\x10\x05\x12\x0e\n\nBARRIER_DO\x10\x06\x32h\n\x13OptionPricerService\x12Q\n\nPriceBatch\x12 .optionpricer.api.PricingRequest\x1a!.optionpricer.api.PricingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICINGRESPONSE_GREEKSENTRY']._loaded_options = None
  _globals['_PRICINGRESPONSE_GREEKSENTRY']._serialized_options = b'8\001'
  _globals['_OPTIONTYPE']._serialized_start=640
  _globals['_OPTIONTYPE']._serialized_end=671
  _globals['_EXOTICTYPE']._serialized_start=673
  _globals['_EXOTICTYPE']._serialized_end=787
  _globals['_OPTIONCONTRACT']._serialized_start=35
  _globals['_OPTIONCONTRACT']._serialized_end=242
  _globals['_MARKETSTATE']._serialized_start=244
  _globals['_MARKETSTATE']._serialized_end=323
  _globals['_PRICINGREQUEST']._serialized_start=326
  _globals['_PRICINGREQUEST']._serialized_end=456
  _globals['_PRICINGRESPONSE']._serialized_start=459
  _globals['_PRICINGRESPONSE']._serialized_end=638
  _globals['_PRICINGRESPONSE_GREEKSENTRY']._serialized_start=593
  _globals['_PRICINGRESPONSE_GREEKSENTRY']._serialized_end=638
  _globals['_OPTIONPRICERSERVICE']._serialized_start=789
  _globals['_OPTIONPRICERSERVICE']._serialized_end=893
# @@protoc_insertion_point(module_scope)
